import { createContext, useContext, useState, useEffect } from "react";

type Language = "ms" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ms";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === "object") {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

const translations: Record<Language, any> = {
  ms: {
    _lang: "ms",
    common: {
      loading: "Memuatkan...",
      save: "Simpan",
      cancel: "Batal",
      delete: "Padam",
      edit: "Edit",
      back: "Kembali",
      submit: "Hantar",
      search: "Cari",
      filter: "Tapis",
      close: "Tutup",
      confirm: "Sahkan",
      yes: "Ya",
      no: "Tidak",
      sku: "SKU",
    },
    runner: {
      dashboard: {
        title: "Dashboard",
        subtitle: "Lihat ringkasan penghantaran anda",
        stats: {
          pendingOffers: "Tawaran Tertunda",
          pendingOffersDesc: "Tawaran penghantaran menunggu respons",
          activeDeliveries: "Penghantaran Aktif",
          activeDeliveriesDesc: "Sedang dalam proses",
          completedToday: "Selesai Hari Ini",
          completedTodayDesc: "Penghantaran selesai",
          totalCompleted: "Jumlah Selesai",
          totalCompletedDesc: "Semua penghantaran",
        },
        activeSection: {
          title: "Penghantaran Aktif",
          desc: "Kerja penghantaran semasa anda",
          viewAll: "Lihat Semua",
          order: "Pesanan",
          to: "Ke",
          amount: "Jumlah",
          updateStatus: "Kemas Kini Status",
          noDeliveries: "Tiada penghantaran aktif",
        },
        pendingSection: {
          title: "Tawaran Tertunda",
          desc: "Tawaran penghantaran diberikan kepada anda",
          accept: "Terima",
          reject: "Tolak",
          noOffers: "Tiada tawaran tertunda",
          expiresIn: "Tamat dalam",
          youllEarn: "Anda Akan Dapat",
          expired: "Tamat Tempoh",
        },
        markers: {
          workshop: "Bengkel",
          supplier: "Pembekal",
          runner: "Pelari",
        },
        toasts: {
          offerAccepted: "Tawaran Diterima",
          offerAcceptedDesc: "Anda telah menerima tawaran penghantaran ini",
          offerRejected: "Tawaran Ditolak",
          offerRejectedDesc: "Anda telah menolak tawaran penghantaran ini",
          statusUpdated: "Status Dikemas Kini",
          statusUpdatedDesc: "Status pesanan telah dikemas kini",
          updateFailed: "Kemas Kini Gagal",
          updateFailedDesc: "Gagal mengemas kini status pesanan",
        },
      },
      jobs: {
        title: "Penghantaran Saya",
        subtitle: "Urus kerja penghantaran dan jejak pendapatan",
        tabs: {
          active: "Aktif",
          available: "Tersedia",
          completed: "Selesai",
        },
        activeTab: {
          title: "Penghantaran Aktif",
          desc: "Kerja penghantaran semasa anda",
          empty: "Tiada penghantaran aktif buat masa ini",
        },
        availableTab: {
          title: "Kerja Tersedia",
          desc: "Kerja penghantaran berdekatan anda",
          empty: "Tiada kerja tersedia buat masa ini",
          acceptJob: "Terima Kerja",
          accepting: "Menerima...",
          youllEarn: "Anda Akan Dapat",
        },
        completedTab: {
          title: "Penghantaran Selesai",
          desc: "Sejarah penghantaran anda",
          empty: "Tiada penghantaran selesai lagi",
          earned: "Diperoleh",
        },
        card: {
          from: "Dari",
          to: "Ke",
          items: "Item",
          itemsCount: "item",
          earnings: "Pendapatan",
          updateStatus: "Kemas Kini Status",
          updating: "Mengemas kini...",
        },
        statusDialog: {
          title: "Kemas Kini Status Penghantaran",
          desc: "Tukar status pesanan #",
          selectStatus: "Pilih status",
          cancel: "Batal",
          update: "Kemas Kini",
        },
        statuses: {
          assignedRunner: "Runner Ditugaskan",
          pickedUp: "Telah Diambil",
          delivering: "Dalam Penghantaran",
          delivered: "Telah Dihantar",
          cancelled: "Dibatalkan",
        },
        toasts: {
          jobAccepted: "Kerja Diterima",
          jobAcceptedDesc: "Anda telah berjaya menerima kerja penghantaran ini",
          jobAcceptFailed: "Gagal menerima kerja. Sila cuba lagi.",
          statusUpdated: "Status Dikemas Kini",
          statusUpdatedDesc: "Status pesanan telah dikemas kini ke",
          error: "Ralat",
          selectStatusError: "Sila pilih status sebelum mengemas kini",
          updateFailed: "Kemas Kini Gagal",
          updateFailedDesc: "Gagal mengemas kini status pesanan",
        },
      },
      wallet: {
        title: "Dompet",
        subtitle: "Urus pendapatan dan baki anda",
        currentBalance: "Baki Semasa",
        availableForWithdrawal: "Tersedia untuk pengeluaran",
        totalEarnings: "Jumlah Pendapatan",
        allTimeEarnings: "Pendapatan sepanjang masa",
        transactionHistory: "Sejarah Transaksi",
        transactionHistoryDesc: "Transaksi dompet terkini anda",
        noTransactions: "Tiada transaksi lagi",
        credit: "Kredit",
        debit: "Debit",
      },
      liveMap: {
        title: "Peta Langsung",
        subtitle: "Jejak penghantaran aktif anda secara langsung",
        selectDelivery: "Pilih Penghantaran Aktif",
        selectDeliveryDesc: "Pilih penghantaran yang hendak dijejak di peta",
        selectDeliveryPlaceholder: "Pilih penghantaran",
        noActiveDeliveries: "Tiada penghantaran aktif pada masa ini",
        loadingLocation: "Memuatkan lokasi semasa anda...",
      },
      settings: {
        title: "Tetapan",
        subtitle: "Urus profil pelari dan keutamaan anda",
        profileInfo: "Maklumat Profil",
        profileInfoDesc: "Kemas kini butiran peribadi anda",
        vehicleInfo: "Maklumat Kenderaan",
        vehicleInfoDesc: "Kemas kini butiran kenderaan anda",
        availability: "Status Ketersediaan",
        availabilityDesc: "Kawal bila anda menerima tawaran penghantaran",
        availableForDeliveries: "Tersedia untuk Penghantaran",
        availabilityToggle: "Toggle untuk kawal jika anda menerima tawaran penghantaran baru",
        notificationPreferences: "Keutamaan Notifikasi",
        notificationPreferencesDesc: "Pilih notifikasi yang anda mahu terima",
        orderNotifications: "Notifikasi Pesanan",
        orderNotificationsDesc: "Terima makluman untuk tawaran penghantaran baru",
        paymentNotifications: "Notifikasi Bayaran",
        paymentNotificationsDesc: "Terima makluman untuk pendapatan dan bayaran",
        marketingNotifications: "Notifikasi Pemasaran",
        marketingNotificationsDesc: "Terima kemas kini tentang promosi dan ciri",
        languageSettings: "Tetapan Bahasa",
        languageSettingsDesc: "Pilih bahasa pilihan anda",
        selectLanguage: "Pilih Bahasa",
        malay: "Bahasa Melayu",
        english: "English",
        name: "Nama",
        email: "Emel",
        phone: "Nombor Telefon",
        vehicleType: "Jenis Kenderaan",
        vehicleNumber: "Nombor Kenderaan",
        vehicleModel: "Model Kenderaan",
        saveProfile: "Simpan Profil",
        saveVehicle: "Simpan Maklumat Kenderaan",
        saveNotifications: "Simpan Keutamaan Notifikasi",
        saving: "Menyimpan...",
        toasts: {
          profileUpdated: "Profil Dikemas Kini",
          profileUpdatedDesc: "Profil anda telah berjaya dikemas kini",
          vehicleUpdated: "Maklumat Kenderaan Dikemas Kini",
          vehicleUpdatedDesc: "Maklumat kenderaan anda telah dikemas kini",
          notificationsUpdated: "Notifikasi Dikemas Kini",
          notificationsUpdatedDesc: "Keutamaan notifikasi anda telah disimpan",
          updateFailed: "Kemas Kini Gagal",
          profileUpdateFailed: "Gagal mengemas kini profil",
          vehicleUpdateFailed: "Gagal mengemas kini maklumat kenderaan",
          notificationUpdateFailed: "Gagal mengemas kini tetapan notifikasi",
        },
      },
      notifications: {
        title: "Notifikasi",
        subtitle: "Kemas kini dengan aktiviti anda",
        allCaughtUp: "Semua selesai!",
        unreadNotifications: "notifikasi belum dibaca",
        markAllRead: "Tandakan Semua Dibaca",
        marking: "Menandakan...",
        allNotifications: "Semua Notifikasi",
        allNotificationsDesc: "Kekal dikemas kini dengan aktiviti anda",
        noNotifications: "Tiada notifikasi lagi",
        new: "Baru",
        time: {
          justNow: "Baru sahaja",
          minutesAgo: "minit yang lalu",
          hoursAgo: "jam yang lalu",
          daysAgo: "hari yang lalu",
        },
        toasts: {
          allMarkedRead: "Semua notifikasi ditandakan sebagai dibaca",
          notificationsMarkedRead: "notifikasi ditandakan sebagai dibaca",
          error: "Ralat",
          markAllFailed: "Gagal menandakan semua notifikasi sebagai dibaca. Sebahagian mungkin telah dikemas kini.",
        },
      },
    },
    customer: {
      dashboard: {
        title: "Dashboard Pelanggan",
        subtitle: "Tempah servis, jejak pembaikan, dan urus kenderaan anda",
        quickActions: "Tindakan Pantas",
        bookAService: "Tempah Servis",
        findWorkshops: "Cari bengkel berhampiran anda dan jadualkan servis kenderaan",
        newBooking: "Tempahan Baharu",
        requestTowing: "Minta Towing",
        getImmediate: "Dapatkan bantuan segera dengan perkhidmatan towing kenderaan",
        requestNow: "Minta Sekarang",
        viewHistory: "Lihat Sejarah",
        trackService: "Jejak tempahan dan rekod servis anda",
        viewRecords: "Lihat Rekod",
        activeBookings: "Tempahan Aktif",
        recentServices: "Servis Terkini",
        noActiveBookings: "Tiada tempahan aktif",
        noRecentServices: "Tiada servis terkini",
        viewDetails: "Lihat Butiran",
        proposalReceived: "Cadangan Diterima",
        workshop: "Bengkel",
        proposedDate: "Tarikh Dicadangkan",
        acceptProposal: "Terima",
        rejectProposal: "Tolak",
        proposalAccepted: "Cadangan Diterima",
        proposalAcceptedDesc: "Tempahan anda telah dikemas kini dengan tarikh baharu",
        proposalRejected: "Cadangan Ditolak",
        proposalRejectedDesc: "Anda telah menolak tarikh yang dicadangkan",
        error: "Ralat",
        failedToUpdate: "Gagal mengemas kini tempahan. Sila cuba lagi.",
        workshopProposedNewDate: "Bengkel Cadangkan Tarikh Baharu",
        reason: "Sebab",
        accepting: "Menerima...",
        accept: "Terima",
        rejecting: "Menolak...",
        reject: "Tolak",
        bookFirstService: "Tempah Servis Pertama Anda",
        yourServiceHistory: "Sejarah servis anda",
        booked: "Ditempah",
        preferred: "Pilihan",
        noServiceHistory: "Tiada sejarah servis",
        notAvailable: "T/A",
      },
      bookings: {
        title: "Tempahan Saya",
        subtitle: "Lihat dan urus tempahan servis anda",
        upcomingBookings: "Tempahan Akan Datang",
        pastBookings: "Tempahan Lepas",
        noBookings: "Tiada tempahan dijumpai",
        bookingDetails: "Butiran Tempahan",
        workshop: "Bengkel",
        dateTime: "Tarikh & Masa",
        vehicle: "Kenderaan",
        serviceType: "Jenis Servis",
        status: "Status",
        actions: "Tindakan",
        viewDetails: "Lihat Butiran",
        cancelBooking: "Batal Tempahan",
        reschedule: "Jadual Semula",
      },
      wallet: {
        title: "Dompet Saya",
        subtitle: "Urus baki dan transaksi anda",
        currentBalance: "Baki Semasa",
        addFunds: "Tambah Dana",
        transactionHistory: "Sejarah Transaksi",
        noTransactions: "Tiada transaksi lagi",
      },
      history: {
        title: "Sejarah Servis",
        subtitle: "Rekod servis dan tempahan anda",
        noHistory: "Tiada sejarah lagi",
      },
      profile: {
        title: "Profil Saya",
        subtitle: "Urus maklumat peribadi anda",
        personalInfo: "Maklumat Peribadi",
        contactInfo: "Maklumat Hubungan",
        vehicles: "Kenderaan Saya",
      },
    },
    workshop: {
      dashboard: {
        title: "Dashboard Bengkel",
        subtitle: "Urus operasi bengkel anda",
        pendingApproval: "Menunggu Kelulusan Admin",
        pendingApprovalDesc: "Akaun bengkel anda sedang menunggu pengesahan oleh pentadbir. Sesetengah ciri mungkin terhad sehingga akaun anda diluluskan.",
        noWorkshop: "Tiada Bengkel Dijumpai",
        noWorkshopDesc: "Anda perlu cipta profil bengkel sebelum boleh akses ciri dashboard.",
      },
      inventory: {
        loading: "Memuatkan inventori...",
        title: "Inventori",
        subtitle: "Urus inventori alat ganti bengkel anda",
        totalItems: "Jumlah Item",
        lowStockItems: "Item Stok Rendah",
        totalValue: "Jumlah Nilai",
        searchPlaceholder: "Cari mengikut nama, SKU, atau kategori...",
        noItems: "Belum ada item inventori lagi",
        noMatches: "Tiada item sepadan dengan carian anda",
        browseMarketplace: "Layari Marketplace",
        lowStock: "Stok Rendah",
        units: "unit",
        each: "setiap",
        pendingOrders: "Pesanan Tertunda",
        lowStockAlertsDesc: "Item dengan kurang daripada 10 unit dalam stok",
        left: "tinggal",
        searchParts: "Cari alat ganti mengikut nama atau SKU...",
        partsInventory: "Inventori Alat Ganti",
        partsInventoryDesc: "Lihat semua alat ganti dan tahap stok semasa",
        noPartsFound: "Tiada alat ganti ditemui sepadan dengan carian anda",
        noPartsInInventory: "Tiada alat ganti dalam inventori",
        purchaseHistory: "Sejarah Pembelian",
        purchaseHistoryDesc: "Rekod alat ganti dan inventori yang dibeli daripada pembekal",
        noPurchaseRecords: "Tiada rekod pembelian dijumpai",
        recentOrders: "Pesanan Terkini",
        recentOrdersDesc: "Pesanan dibuat dengan pembekal",
        noOrdersFound: "Tiada pesanan dijumpai",
        totalAmount: "Jumlah Keseluruhan",
        generating: "Menjana...",
        invoice: "Invois",
        tableHeaders: {
          sku: "SKU",
          name: "Nama",
          category: "Kategori",
          stock: "Stok",
          price: "Harga",
          value: "Nilai",
          date: "Tarikh",
          item: "Item",
          quantity: "Kuantiti",
          costUnit: "Kos/Unit",
          totalCost: "Jumlah Kos",
          actions: "Tindakan",
        },
      },
      cart: {
        checkout: "Daftar Keluar",
        reviewOrder: "Semak pesanan anda dan lengkapkan pembelian",
        emptyCart: "Troli anda kosong",
        addPartsPrompt: "Tambah alat ganti dari marketplace",
        browseMarketplace: "Layari Marketplace",
        orderItems: "Item Pesanan",
        supplierOrder: "Pesanan Pembekal",
        suppliers: "pembekal",
        items: "item",
        qty: "Ktt",
        deliveryOptions: "Pilihan Penghantaran",
        deliveryPrompt: "Pilih cara anda ingin terima alat ganti",
        pickup: "Ambil Sendiri",
        pickupDesc: "Ambil alat ganti terus dari pembekal",
        runnerDelivery: "Penghantaran Runner",
        runnerDeliveryDesc: "Runner hantar alat ganti ke bengkel anda",
        deliveryAddress: "Alamat Penghantaran *",
        deliveryAddressPlaceholder: "Masukkan alamat bengkel anda...",
        orderNotes: "Nota Pesanan (Pilihan)",
        orderNotesPlaceholder: "Tambah arahan khas atau nota...",
        bankTransferRequired: "Pesanan Dibuat - Pindahan Bank Diperlukan",
        transferPrompt: "Sila pindahkan RM{amount} ke akaun di bawah:",
        bank: "Bank:",
        account: "Akaun:",
        name: "Nama:",
        reference: "Rujukan:",
        viewMyOrders: "Lihat Pesanan Saya",
        paymentMethod: "Kaedah Pembayaran",
        paymentPrompt: "Pilih cara anda ingin bayar",
        wallet: "Dompet",
        walletDesc: "Bayar terus guna baki dompet anda",
        bankTransfer: "Pindahan Bank",
        bankTransferDesc: "Pindah ke akaun bank kami (pengesahan manual)",
        qrCode: "Kod QR (DuitNow)",
        comingSoon: "Akan Datang",
        qrCodeDesc: "Imbas kod QR dengan app banking anda",
        orderSummary: "Ringkasan Pesanan",
        subtotal: "Subjumlah",
        delivery: "Penghantaran",
        free: "Percuma",
        calculating: "Mengira...",
        total: "Jumlah",
        insufficientBalance: "Baki dompet tidak mencukupi. Sila tambah nilai atau pilih kaedah pembayaran lain.",
        calculatingDelivery: "Mengira Penghantaran...",
        processing: "Memproses...",
        placeOrder: "Buat Pesanan",
        termsAgreement: "Dengan membuat pesanan ini, anda bersetuju dengan terma dan syarat kami",
        toasts: {
          addressRequired: "Alamat penghantaran diperlukan",
          addressRequiredDesc: "Sila masukkan alamat penghantaran untuk penghantaran runner",
          calculatingCharge: "Mengira caj penghantaran",
          calculatingChargeDesc: "Sila tunggu sementara kami kira yuran penghantaran anda",
          orderCreated: "Pesanan berjaya dibuat",
          completeBankTransfer: "Sila lengkapkan pindahan bank untuk teruskan",
          paymentSuccessful: "Pembayaran berjaya",
          orderPlacedWallet: "Pesanan berjaya dibuat menggunakan dompet",
          orderPlacedPayment: "Pesanan berjaya dibuat menggunakan kaedah pembayaran",
          orderFailed: "Gagal membuat pesanan",
          tryAgain: "Sila cuba lagi",
          insufficientBalanceDetail: "Baki dompet tidak mencukupi. Diperlukan: RM{required}, Tersedia: RM{available}",
        },
      },
    },
    admin: {
      dashboard: {
        title: "Dashboard Admin",
        subtitle: "Urus platform dan pengguna",
      },
    },
    supplier: {
      dashboard: {
        title: "Dashboard Pembekal",
        subtitle: "Urus produk dan pesanan",
        accessDenied: "Akses Ditolak",
        needSupplierRole: "Anda perlu menjadi pembekal untuk mengakses halaman ini.",
        categories: {
          oem: "OEM",
          lubricant: "Pelincir",
          battery: "Bateri",
          tyre: "Tayar",
          tools: "Alatan",
          accessories: "Aksesori",
          other: "Lain-lain",
          engine: "Enjin",
          transmission: "Transmisi",
          brake: "Brek",
          suspension: "Suspensi",
          electrical: "Elektrik",
          cooling: "Penyejukan",
          body: "Badan",
          interior: "Dalaman",
          exterior: "Luaran",
          wheel: "Roda",
          filters: "Penapis",
          ignition: "Pencucuhan",
          fluids: "Cecair",
        },
        validation: {
          productNameRequired: "Nama produk diperlukan",
          priceGreaterThanZero: "Harga mesti lebih besar daripada 0",
          stockMinZero: "Stok mesti 0 atau lebih besar",
          validUrl: "Mestilah URL yang sah",
          maxImages: "Maksimum 5 gambar dibenarkan",
        },
        toasts: {
          success: "Berjaya",
          error: "Ralat",
          productCreated: "Produk berjaya dicipta",
          productCreateFailed: "Gagal mencipta produk",
          productUpdated: "Produk berjaya dikemas kini",
          productUpdateFailed: "Gagal mengemas kini produk",
          productDeleted: "Produk berjaya dipadam",
          productDeleteFailed: "Gagal memadam produk",
          orderAccepted: "Pesanan berjaya diterima",
          orderAcceptFailed: "Gagal menerima pesanan",
          orderRejected: "Pesanan berjaya ditolak",
          orderRejectFailed: "Gagal menolak pesanan",
        },
        dialogs: {
          editProduct: "Edit Produk",
          addProduct: "Tambah Produk Baharu",
          updateDesc: "Kemas kini butiran produk di bawah",
          createDesc: "Cipta produk baharu untuk inventori anda",
          deleteProduct: "Padam Produk",
          deleteConfirm: "Adakah anda pasti mahu memadam produk ini? Tindakan ini tidak boleh dibatalkan.",
        },
        buttons: {
          addProduct: "Tambah Produk",
          cancel: "Batal",
          updateProduct: "Kemas Kini Produk",
          createProduct: "Cipta Produk",
          accept: "Terima",
          reject: "Tolak",
          delete: "Padam",
        },
        forms: {
          productName: "Nama Produk",
          productNamePlaceholder: "cth., Minyak Enjin Castrol 5W-30",
          category: "Kategori",
          categoryPlaceholder: "Pilih kategori",
          skuLabel: "SKU (Pilihan)",
          skuPlaceholder: "cth., EO-5W30-1L",
          price: "Harga (RM)",
          pricePlaceholder: "0.00",
          stockQuantity: "Kuantiti Stok",
          stockPlaceholder: "0",
          description: "Penerangan (Pilihan)",
          descriptionPlaceholder: "Penerangan produk, spesifikasi, ciri-ciri...",
          images: "Gambar Produk (Maks 5)",
          imagesDesc: "Masukkan URL gambar untuk produk anda",
          imagePlaceholder: "https://contoh.com/gambar.jpg",
          addImage: "Tambah URL Gambar",
        },
        cards: {
          totalProducts: "Jumlah Produk",
          totalStock: "Jumlah Stok",
          lowStockItems: "Item Stok Rendah",
          pendingOrders: "Pesanan Tertunda",
          productInventory: "Inventori Produk",
          productInventoryDesc: "Urus katalog produk dan tahap stok anda",
          incomingOrders: "Pesanan Masuk",
          incomingOrdersDesc: "Urus pesanan daripada bengkel",
          lowStock: "Stok Rendah",
        },
        tabs: {
          products: "Produk",
          orders: "Pesanan",
          messages: "Mesej",
        },
        alert: {
          pendingApproval: "Menunggu Kelulusan Admin",
          pendingApprovalDesc: "Akaun pembekal anda sedang menunggu pengesahan oleh pentadbir. Sesetengah ciri mungkin terhad sehingga akaun anda diluluskan.",
        },
        empty: {
          loading: "Memuatkan produk...",
          noProducts: "Tiada produk lagi. Klik \"Tambah Produk\" untuk cipta produk pertama anda.",
          noOrders: "Tiada pesanan lagi",
        },
        stock: "Stok",
        order: "Pesanan #",
        totalAmount: "Jumlah Keseluruhan:",
        deliveryType: "Jenis Penghantaran:",
      },
      bulkUpload: {
        title: "Tambah Produk",
        description: "Pilih kaedah pilihan anda untuk menambah produk",
        manualEntry: "Entry Manual",
        csvImport: "Import CSV",
        aiImageUpload: "Muat Naik Gambar AI",
      },
      csvUpload: {
        title: "Muat Naik Fail CSV",
        description: "Import berbilang produk sekaligus menggunakan format CSV",
        downloadTemplate: "Muat Turun Templat",
        selectFile: "Pilih Fail CSV",
        preview: "Pratonton (5 baris pertama)",
        tableName: "Nama",
        tableSKU: "SKU",
        tableCategory: "Kategori",
        tablePrice: "Harga",
        tableStock: "Stok",
        importing: "Mengimport...",
        importProducts: "Import Produk",
        toasts: {
          invalidFileTitle: "Fail Tidak Sah",
          invalidFileDesc: "Sila muat naik fail CSV",
          noFileTitle: "Tiada Fail",
          noFileDesc: "Sila pilih fail CSV untuk dimuat naik",
          successTitle: "Berjaya",
          successDesc: "produk diimport dengan jayanya",
          uploadFailedTitle: "Muat Naik Gagal",
          uploadFailedDesc: "Gagal mengimport CSV. Sila semak format fail anda.",
        },
      },
      manualForm: {
        productImages: "Gambar Produk",
        max5: "Maks 5",
        imageUrlHint: "Masukkan URL gambar untuk produk anda",
        takePhoto: "Ambil Gambar",
        addImageUrl: "Tambah URL Gambar",
        adding: "Menambah...",
        addProduct: "Tambah Produk",
        success: "Berjaya",
        productAdded: "Produk berjaya ditambah",
        error: "Ralat",
        productAddFailed: "Gagal menambah produk",
        cameraNotAvailable: "Kamera Tidak Tersedia",
        cameraWebNotSupported: "Kamera hanya tersedia di aplikasi mudah alih",
        imageUploaded: "Gambar Dimuat Naik",
        imageUploadedSuccess: "Gambar produk berjaya dimuat naik",
        cameraError: "Ralat Kamera",
        cameraErrorGeneric: "Gagal mengambil gambar. Sila cuba lagi.",
      },
    },
    marketplace: {
      by: "Oleh",
      stock: "Stok",
      outOfStock: "Habis Stok",
      code: "Kod",
      description: "Penerangan",
      compatibility: "Keserasian",
      make: "Jenama",
      model: "Model",
      year: "Tahun",
      quantity: "Kuantiti",
      buyNow: "Beli Sekarang",
      addToCart: "Tambah ke Troli",
      chat: "Chat",
      selectDelivery: "Pilih Kaedah Penghantaran",
      selectDeliveryDesc: "Pilih sama ada anda ingin ambil sendiri atau guna perkhidmatan runner",
      pickup: "Ambil Sendiri",
      free: "Percuma",
      pickupDesc: "Ambil barang di lokasi pembekal",
      pickupIdInfo: "ID pickup unik akan dijana untuk anda dan pembekal gunakan untuk pengesahan",
      runnerDelivery: "Penghantaran Runner",
      calculated: "Dikira",
      runnerDeliveryDesc: "Runner akan hantar terus ke lokasi anda",
    },
    towing: {
      dashboard: {
        title: "Dashboard Towing",
        subtitle: "Urus permintaan towing dan jejak pendapatan anda",
        todaysRevenue: "Pendapatan Hari Ini",
        totalRevenueToday: "Jumlah pendapatan hari ini",
        activeRequests: "Permintaan Aktif",
        currentlyActive: "Permintaan aktif sekarang",
        completedToday: "Selesai Hari Ini",
        completedRequests: "Permintaan yang diselesaikan hari ini",
        pendingRequests: "Permintaan Tertunda",
        availableRequests: "Permintaan yang tersedia",
        activeServiceRequests: "Permintaan Servis Aktif",
        completingService: "Selesaikan servis untuk permintaan ini",
        noActiveRequests: "Tiada permintaan aktif",
        availableNow: "Permintaan Tersedia Sekarang",
        acceptNew: "Terima permintaan towing baharu",
        noAvailableRequests: "Tiada permintaan tersedia",
        requestAccepted: "Permintaan Diterima",
        assignedToRequest: "Anda telah ditugaskan untuk permintaan towing ini.",
        error: "Ralat",
        failedToAccept: "Gagal menerima permintaan. Sila cuba lagi.",
        customer: "Pelanggan",
        location: "Lokasi",
        estimatedCost: "Kos Anggaran",
        description: "Penerangan",
        acceptRequest: "Terima Permintaan",
        activeRequestsTitle: "Permintaan Aktif",
        yourCurrentJobs: "Kerja towing semasa anda",
        viewAll: "Lihat Semua",
        customerRequest: "Permintaan Pelanggan",
        from: "Dari",
        to: "Ke",
        pending: "Tertunda",
        updateStatus: "Kemas Kini Status",
        pendingRequestsTitle: "Permintaan Tertunda",
        newRequestsNear: "Permintaan towing baharu berhampiran anda",
        newRequest: "Permintaan Baharu",
        quotePending: "Sebut harga tertunda",
        accepting: "Menerima...",
        noPendingRequests: "Tiada permintaan tertunda",
      },
    },
    statuses: {
      created: "Dicipta",
      accepted: "Diterima",
      preparing: "Menyediakan",
      assigned_runner: "Runner Ditugaskan",
      delivering: "Menghantar",
      delivered: "Dihantar",
      cancelled: "Dibatalkan",
      pending: "Menunggu",
      in_progress: "Dalam Proses",
      completed: "Selesai",
      assigned: "Ditugaskan",
      en_route: "Dalam Perjalanan",
      approved: "Diluluskan",
      rejected: "Ditolak",
    },
  },
  en: {
    _lang: "en",
    common: {
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      back: "Back",
      submit: "Submit",
      search: "Search",
      filter: "Filter",
      close: "Close",
      confirm: "Confirm",
      yes: "Yes",
      no: "No",
      sku: "SKU",
    },
    runner: {
      dashboard: {
        title: "Dashboard",
        subtitle: "View your delivery summary",
        stats: {
          pendingOffers: "Pending Offers",
          pendingOffersDesc: "Delivery offers awaiting response",
          activeDeliveries: "Active Deliveries",
          activeDeliveriesDesc: "Currently in progress",
          completedToday: "Completed Today",
          completedTodayDesc: "Deliveries completed",
          totalCompleted: "Total Completed",
          totalCompletedDesc: "All time deliveries",
        },
        activeSection: {
          title: "Active Deliveries",
          desc: "Your current delivery jobs",
          viewAll: "View All",
          order: "Order",
          to: "To",
          amount: "Amount",
          updateStatus: "Update Status",
          noDeliveries: "No active deliveries",
        },
        pendingSection: {
          title: "Pending Offers",
          desc: "Delivery offers assigned to you",
          accept: "Accept",
          reject: "Reject",
          noOffers: "No pending offers",
          expiresIn: "Expires in",
          youllEarn: "You'll Earn",
          expired: "Expired",
        },
        markers: {
          workshop: "Workshop",
          supplier: "Supplier",
          runner: "Runner",
        },
        toasts: {
          offerAccepted: "Offer Accepted",
          offerAcceptedDesc: "You have successfully accepted this delivery offer",
          offerRejected: "Offer Rejected",
          offerRejectedDesc: "You have rejected this delivery offer",
          statusUpdated: "Status Updated",
          statusUpdatedDesc: "Order status has been updated",
          updateFailed: "Update Failed",
          updateFailedDesc: "Failed to update order status",
        },
      },
      jobs: {
        title: "My Deliveries",
        subtitle: "Manage your delivery jobs and track earnings",
        tabs: {
          active: "Active",
          available: "Available",
          completed: "Completed",
        },
        activeTab: {
          title: "Active Deliveries",
          desc: "Your current delivery jobs",
          empty: "No active deliveries at the moment",
        },
        availableTab: {
          title: "Available Jobs",
          desc: "Delivery jobs near you",
          empty: "No available jobs at the moment",
          acceptJob: "Accept Job",
          accepting: "Accepting...",
          youllEarn: "You'll Earn",
        },
        completedTab: {
          title: "Completed Deliveries",
          desc: "Your delivery history",
          empty: "No completed deliveries yet",
          earned: "Earned",
        },
        card: {
          from: "From",
          to: "To",
          items: "Items",
          itemsCount: "items",
          earnings: "Earnings",
          updateStatus: "Update Status",
          updating: "Updating...",
        },
        statusDialog: {
          title: "Update Delivery Status",
          desc: "Change the status of order #",
          selectStatus: "Select status",
          cancel: "Cancel",
          update: "Update",
        },
        statuses: {
          assignedRunner: "Assigned Runner",
          pickedUp: "Picked Up",
          delivering: "Delivering",
          delivered: "Delivered",
          cancelled: "Cancelled",
        },
        toasts: {
          jobAccepted: "Job Accepted",
          jobAcceptedDesc: "You have successfully accepted this delivery job",
          jobAcceptFailed: "Failed to accept job. Please try again.",
          statusUpdated: "Status Updated",
          statusUpdatedDesc: "Order status updated to",
          error: "Error",
          selectStatusError: "Please select a status before updating",
          updateFailed: "Update Failed",
          updateFailedDesc: "Failed to update order status",
        },
      },
      wallet: {
        title: "Wallet",
        subtitle: "Manage your earnings and balance",
        currentBalance: "Current Balance",
        availableForWithdrawal: "Available for withdrawal",
        totalEarnings: "Total Earnings",
        allTimeEarnings: "All time earnings",
        transactionHistory: "Transaction History",
        transactionHistoryDesc: "Your recent wallet transactions",
        noTransactions: "No transactions yet",
        credit: "Credit",
        debit: "Debit",
      },
      liveMap: {
        title: "Live Map",
        subtitle: "Track your active deliveries in real-time",
        selectDelivery: "Select Active Delivery",
        selectDeliveryDesc: "Choose which delivery to track on the map",
        selectDeliveryPlaceholder: "Select delivery",
        noActiveDeliveries: "No active deliveries at the moment",
        loadingLocation: "Loading your current location...",
      },
      settings: {
        title: "Settings",
        subtitle: "Manage your runner profile and preferences",
        profileInfo: "Profile Information",
        profileInfoDesc: "Update your personal details",
        vehicleInfo: "Vehicle Information",
        vehicleInfoDesc: "Update your vehicle details",
        availability: "Availability Status",
        availabilityDesc: "Control when you receive delivery offers",
        availableForDeliveries: "Available for Deliveries",
        availabilityToggle: "Toggle to control if you receive new delivery offers",
        notificationPreferences: "Notification Preferences",
        notificationPreferencesDesc: "Choose what notifications you want to receive",
        orderNotifications: "Order Notifications",
        orderNotificationsDesc: "Receive alerts for new delivery offers",
        paymentNotifications: "Payment Notifications",
        paymentNotificationsDesc: "Receive alerts for earnings and payments",
        marketingNotifications: "Marketing Notifications",
        marketingNotificationsDesc: "Receive updates about promotions and features",
        languageSettings: "Language Settings",
        languageSettingsDesc: "Choose your preferred language",
        selectLanguage: "Select Language",
        malay: "Bahasa Melayu",
        english: "English",
        name: "Name",
        email: "Email",
        phone: "Phone Number",
        vehicleType: "Vehicle Type",
        vehicleNumber: "Vehicle Number",
        vehicleModel: "Vehicle Model",
        saveProfile: "Save Profile",
        saveVehicle: "Save Vehicle Info",
        saveNotifications: "Save Notification Preferences",
        saving: "Saving...",
        toasts: {
          profileUpdated: "Profile Updated",
          profileUpdatedDesc: "Your profile has been updated successfully",
          vehicleUpdated: "Vehicle Info Updated",
          vehicleUpdatedDesc: "Your vehicle information has been updated",
          notificationsUpdated: "Notifications Updated",
          notificationsUpdatedDesc: "Your notification preferences have been saved",
          updateFailed: "Update Failed",
          profileUpdateFailed: "Failed to update profile",
          vehicleUpdateFailed: "Failed to update vehicle information",
          notificationUpdateFailed: "Failed to update notification settings",
        },
      },
      notifications: {
        title: "Notifications",
        subtitle: "Stay updated with your activities",
        allCaughtUp: "All caught up!",
        unreadNotifications: "unread notifications",
        markAllRead: "Mark All as Read",
        marking: "Marking...",
        allNotifications: "All Notifications",
        allNotificationsDesc: "Stay updated with your activities",
        noNotifications: "No notifications yet",
        new: "New",
        time: {
          justNow: "Just now",
          minutesAgo: "m ago",
          hoursAgo: "h ago",
          daysAgo: "d ago",
        },
        toasts: {
          allMarkedRead: "All notifications marked as read",
          notificationsMarkedRead: "notifications marked as read",
          error: "Error",
          markAllFailed: "Failed to mark all notifications as read. Some may have been updated.",
        },
      },
    },
    customer: {
      dashboard: {
        title: "Customer Dashboard",
        subtitle: "Book services, track repairs, and manage your vehicles",
        quickActions: "Quick Actions",
        bookAService: "Book a Service",
        findWorkshops: "Find workshops near you and schedule your vehicle service",
        newBooking: "New Booking",
        requestTowing: "Request Towing",
        getImmediate: "Get immediate help with vehicle towing services",
        requestNow: "Request Now",
        viewHistory: "View History",
        trackService: "Track your bookings and service records",
        viewRecords: "View Records",
        activeBookings: "Active Bookings",
        recentServices: "Recent Services",
        noActiveBookings: "No active bookings",
        noRecentServices: "No recent services",
        viewDetails: "View Details",
        proposalReceived: "Proposal Received",
        workshop: "Workshop",
        proposedDate: "Proposed Date",
        acceptProposal: "Accept",
        rejectProposal: "Reject",
        proposalAccepted: "Proposal Accepted",
        proposalAcceptedDesc: "Your booking has been updated with the new date",
        proposalRejected: "Proposal Rejected",
        proposalRejectedDesc: "You have rejected the proposed date",
        error: "Error",
        failedToUpdate: "Failed to update booking. Please try again.",
        workshopProposedNewDate: "Workshop Proposed New Date",
        reason: "Reason",
        accepting: "Accepting...",
        accept: "Accept",
        rejecting: "Rejecting...",
        reject: "Reject",
        bookFirstService: "Book Your First Service",
        yourServiceHistory: "Your service history",
        booked: "Booked",
        preferred: "Preferred",
        noServiceHistory: "No service history",
        notAvailable: "N/A",
      },
      bookings: {
        title: "My Bookings",
        subtitle: "View and manage your service bookings",
        upcomingBookings: "Upcoming Bookings",
        pastBookings: "Past Bookings",
        noBookings: "No bookings found",
        bookingDetails: "Booking Details",
        workshop: "Workshop",
        dateTime: "Date & Time",
        vehicle: "Vehicle",
        serviceType: "Service Type",
        status: "Status",
        actions: "Actions",
        viewDetails: "View Details",
        cancelBooking: "Cancel Booking",
        reschedule: "Reschedule",
      },
      wallet: {
        title: "My Wallet",
        subtitle: "Manage your balance and transactions",
        currentBalance: "Current Balance",
        addFunds: "Add Funds",
        transactionHistory: "Transaction History",
        noTransactions: "No transactions yet",
      },
      history: {
        title: "Service History",
        subtitle: "Your service and booking records",
        noHistory: "No history yet",
      },
      profile: {
        title: "My Profile",
        subtitle: "Manage your personal information",
        personalInfo: "Personal Information",
        contactInfo: "Contact Information",
        vehicles: "My Vehicles",
      },
    },
    workshop: {
      dashboard: {
        title: "Workshop Dashboard",
        subtitle: "Manage your workshop operations",
        pendingApproval: "Pending Admin Approval",
        pendingApprovalDesc: "Your workshop account is currently pending verification by an administrator. Some features may be limited until your account is approved.",
        noWorkshop: "No Workshop Found",
        noWorkshopDesc: "You need to create a workshop profile before you can access the dashboard features.",
      },
      inventory: {
        loading: "Loading inventory...",
        title: "Inventory",
        subtitle: "Manage your workshop's parts inventory",
        totalItems: "Total Items",
        lowStockItems: "Low Stock Items",
        totalValue: "Total Value",
        searchPlaceholder: "Search by name, SKU, or category...",
        noItems: "No inventory items yet",
        noMatches: "No items match your search",
        browseMarketplace: "Browse Marketplace",
        lowStock: "Low Stock",
        units: "units",
        each: "each",
        pendingOrders: "Pending Orders",
        lowStockAlertsDesc: "Items with less than 10 units in stock",
        left: "left",
        searchParts: "Search parts by name or SKU...",
        partsInventory: "Parts Inventory",
        partsInventoryDesc: "View all parts and their current stock levels",
        noPartsFound: "No parts found matching your search",
        noPartsInInventory: "No parts in inventory",
        purchaseHistory: "Purchase History",
        purchaseHistoryDesc: "Record of parts and inventory purchased from suppliers",
        noPurchaseRecords: "No purchase records found",
        recentOrders: "Recent Orders",
        recentOrdersDesc: "Orders placed with suppliers",
        noOrdersFound: "No orders found",
        totalAmount: "Total Amount",
        generating: "Generating...",
        invoice: "Invoice",
        tableHeaders: {
          sku: "SKU",
          name: "Name",
          category: "Category",
          stock: "Stock",
          price: "Price",
          value: "Value",
          date: "Date",
          item: "Item",
          quantity: "Quantity",
          costUnit: "Cost/Unit",
          totalCost: "Total Cost",
          actions: "Actions",
        },
      },
      cart: {
        checkout: "Checkout",
        reviewOrder: "Review your order and complete purchase",
        emptyCart: "Your cart is empty",
        addPartsPrompt: "Add some parts from the marketplace",
        browseMarketplace: "Browse Marketplace",
        orderItems: "Order Items",
        supplierOrder: "Supplier Order",
        suppliers: "supplier(s)",
        items: "item(s)",
        qty: "Qty",
        deliveryOptions: "Delivery Options",
        deliveryPrompt: "Choose how you want to receive your parts",
        pickup: "Pickup",
        pickupDesc: "Pick up parts directly from the supplier",
        runnerDelivery: "Runner Delivery",
        runnerDeliveryDesc: "Have a runner deliver parts to your workshop",
        deliveryAddress: "Delivery Address *",
        deliveryAddressPlaceholder: "Enter your workshop address...",
        orderNotes: "Order Notes (Optional)",
        orderNotesPlaceholder: "Add any special instructions or notes...",
        bankTransferRequired: "Order Created - Bank Transfer Required",
        transferPrompt: "Please transfer RM{amount} to the account below:",
        bank: "Bank:",
        account: "Account:",
        name: "Name:",
        reference: "Reference:",
        viewMyOrders: "View My Orders",
        paymentMethod: "Payment Method",
        paymentPrompt: "Choose how you want to pay",
        wallet: "Wallet",
        walletDesc: "Pay instantly using your wallet balance",
        bankTransfer: "Bank Transfer",
        bankTransferDesc: "Transfer to our bank account (manual verification)",
        qrCode: "QR Code (DuitNow)",
        comingSoon: "Coming Soon",
        qrCodeDesc: "Scan QR code with your banking app",
        orderSummary: "Order Summary",
        subtotal: "Subtotal",
        delivery: "Delivery",
        free: "Free",
        calculating: "Calculating...",
        total: "Total",
        insufficientBalance: "Insufficient wallet balance. Please top up or choose another payment method.",
        calculatingDelivery: "Calculating Delivery...",
        processing: "Processing...",
        placeOrder: "Place Order",
        termsAgreement: "By placing this order, you agree to our terms and conditions",
        toasts: {
          addressRequired: "Delivery address required",
          addressRequiredDesc: "Please enter a delivery address for runner delivery",
          calculatingCharge: "Calculating delivery charge",
          calculatingChargeDesc: "Please wait while we calculate your delivery fees",
          orderCreated: "Order created successfully",
          completeBankTransfer: "Please complete bank transfer to proceed",
          paymentSuccessful: "Payment successful",
          orderPlacedWallet: "Order placed successfully using wallet",
          orderPlacedPayment: "Order placed successfully using payment method",
          orderFailed: "Failed to place order",
          tryAgain: "Please try again",
          insufficientBalanceDetail: "Insufficient wallet balance. Required: RM{required}, Available: RM{available}",
        },
      },
    },
    admin: {
      dashboard: {
        title: "Admin Dashboard",
        subtitle: "Manage platform and users",
      },
    },
    supplier: {
      dashboard: {
        title: "Supplier Dashboard",
        subtitle: "Manage products and orders",
        accessDenied: "Access Denied",
        needSupplierRole: "You need to be a supplier to access this page.",
        categories: {
          oem: "OEM",
          lubricant: "Lubricant",
          battery: "Battery",
          tyre: "Tyre",
          tools: "Tools",
          accessories: "Accessories",
          other: "Other",
          engine: "Engine",
          transmission: "Transmission",
          brake: "Brake",
          suspension: "Suspension",
          electrical: "Electrical",
          cooling: "Cooling",
          body: "Body",
          interior: "Interior",
          exterior: "Exterior",
          wheel: "Wheel",
          filters: "Filters",
          ignition: "Ignition",
          fluids: "Fluids",
        },
        validation: {
          productNameRequired: "Product name is required",
          priceGreaterThanZero: "Price must be greater than 0",
          stockMinZero: "Stock must be 0 or greater",
          validUrl: "Must be a valid URL",
          maxImages: "Maximum 5 images allowed",
        },
        toasts: {
          success: "Success",
          error: "Error",
          productCreated: "Product created successfully",
          productCreateFailed: "Failed to create product",
          productUpdated: "Product updated successfully",
          productUpdateFailed: "Failed to update product",
          productDeleted: "Product deleted successfully",
          productDeleteFailed: "Failed to delete product",
          orderAccepted: "Order accepted successfully",
          orderAcceptFailed: "Failed to accept order",
          orderRejected: "Order rejected successfully",
          orderRejectFailed: "Failed to reject order",
        },
        dialogs: {
          editProduct: "Edit Product",
          addProduct: "Add New Product",
          updateDesc: "Update product details below",
          createDesc: "Create a new product for your inventory",
          deleteProduct: "Delete Product",
          deleteConfirm: "Are you sure you want to delete this product? This action cannot be undone.",
        },
        buttons: {
          addProduct: "Add Product",
          cancel: "Cancel",
          updateProduct: "Update Product",
          createProduct: "Create Product",
          accept: "Accept",
          reject: "Reject",
          delete: "Delete",
        },
        forms: {
          productName: "Product Name",
          productNamePlaceholder: "e.g., Castrol Engine Oil 5W-30",
          category: "Category",
          categoryPlaceholder: "Select category",
          skuLabel: "SKU (Optional)",
          skuPlaceholder: "e.g., EO-5W30-1L",
          price: "Price (RM)",
          pricePlaceholder: "0.00",
          stockQuantity: "Stock Quantity",
          stockPlaceholder: "0",
          description: "Description (Optional)",
          descriptionPlaceholder: "Product description, specifications, features...",
          images: "Product Images (Max 5)",
          imagesDesc: "Enter image URLs for your product",
          imagePlaceholder: "https://example.com/image.jpg",
          addImage: "Add Image URL",
        },
        cards: {
          totalProducts: "Total Products",
          totalStock: "Total Stock",
          lowStockItems: "Low Stock Items",
          pendingOrders: "Pending Orders",
          productInventory: "Product Inventory",
          productInventoryDesc: "Manage your product catalog and stock levels",
          incomingOrders: "Incoming Orders",
          incomingOrdersDesc: "Manage orders from workshops",
          lowStock: "Low Stock",
        },
        tabs: {
          products: "Products",
          orders: "Orders",
          messages: "Messages",
        },
        alert: {
          pendingApproval: "Pending Admin Approval",
          pendingApprovalDesc: "Your supplier account is currently pending verification by an administrator. Some features may be limited until your account is approved.",
        },
        empty: {
          loading: "Loading products...",
          noProducts: "No products yet. Click \"Add Product\" to create your first product.",
          noOrders: "No orders yet",
        },
        stock: "Stock",
        order: "Order #",
        totalAmount: "Total Amount:",
        deliveryType: "Delivery Type:",
      },
      bulkUpload: {
        title: "Add Products",
        description: "Choose your preferred method to add products",
        manualEntry: "Manual Entry",
        csvImport: "CSV Import",
        aiImageUpload: "AI Image Upload",
      },
      csvUpload: {
        title: "Upload CSV File",
        description: "Import multiple products at once using CSV format",
        downloadTemplate: "Download Template",
        selectFile: "Select CSV File",
        preview: "Preview (first 5 rows)",
        tableName: "Name",
        tableSKU: "SKU",
        tableCategory: "Category",
        tablePrice: "Price",
        tableStock: "Stock",
        importing: "Importing...",
        importProducts: "Import Products",
        toasts: {
          invalidFileTitle: "Invalid File",
          invalidFileDesc: "Please upload a CSV file",
          noFileTitle: "No File",
          noFileDesc: "Please select a CSV file to upload",
          successTitle: "Success",
          successDesc: "products imported successfully",
          uploadFailedTitle: "Upload Failed",
          uploadFailedDesc: "Failed to import CSV. Please check your file format.",
        },
      },
      manualForm: {
        productImages: "Product Images",
        max5: "Max 5",
        imageUrlHint: "Enter image URLs for your product",
        takePhoto: "Take Photo",
        addImageUrl: "Add Image URL",
        adding: "Adding...",
        addProduct: "Add Product",
        success: "Success",
        productAdded: "Product added successfully",
        error: "Error",
        productAddFailed: "Failed to add product",
        cameraNotAvailable: "Camera Not Available",
        cameraWebNotSupported: "Camera is only available on mobile app",
        imageUploaded: "Image Uploaded",
        imageUploadedSuccess: "Product image uploaded successfully",
        cameraError: "Camera Error",
        cameraErrorGeneric: "Failed to capture image. Please try again.",
      },
    },
    marketplace: {
      by: "By",
      stock: "Stock",
      outOfStock: "Out of Stock",
      code: "Code",
      description: "Description",
      compatibility: "Compatibility",
      make: "Make",
      model: "Model",
      year: "Year",
      quantity: "Quantity",
      buyNow: "Buy Now",
      addToCart: "Add to Cart",
      chat: "Chat",
      selectDelivery: "Select Delivery Method",
      selectDeliveryDesc: "Choose whether you want to pickup or use runner delivery",
      pickup: "Pickup",
      free: "Free",
      pickupDesc: "Collect items at supplier location",
      pickupIdInfo: "A unique pickup ID will be generated for you and the supplier to use for verification",
      runnerDelivery: "Runner Delivery",
      calculated: "Calculated",
      runnerDeliveryDesc: "Runner will deliver directly to your location",
    },
    towing: {
      dashboard: {
        title: "Towing Dashboard",
        subtitle: "Manage towing requests and track your revenue",
        todaysRevenue: "Today's Revenue",
        totalRevenueToday: "Total revenue today",
        activeRequests: "Active Requests",
        currentlyActive: "Currently active requests",
        completedToday: "Completed Today",
        completedRequests: "Requests completed today",
        pendingRequests: "Pending Requests",
        availableRequests: "Available requests",
        activeServiceRequests: "Active Service Requests",
        completingService: "Complete service for these requests",
        noActiveRequests: "No active requests",
        availableNow: "Available Requests Now",
        acceptNew: "Accept new towing requests",
        noAvailableRequests: "No available requests",
        requestAccepted: "Request Accepted",
        assignedToRequest: "You have been assigned to this towing request.",
        error: "Error",
        failedToAccept: "Failed to accept request. Please try again.",
        customer: "Customer",
        location: "Location",
        estimatedCost: "Estimated Cost",
        description: "Description",
        acceptRequest: "Accept Request",
        activeRequestsTitle: "Active Requests",
        yourCurrentJobs: "Your current towing jobs",
        viewAll: "View All",
        customerRequest: "Customer Request",
        from: "From",
        to: "To",
        pending: "Pending",
        updateStatus: "Update Status",
        pendingRequestsTitle: "Pending Requests",
        newRequestsNear: "New towing requests near you",
        newRequest: "New Request",
        quotePending: "Quote pending",
        accepting: "Accepting...",
        noPendingRequests: "No pending requests",
      },
    },
    statuses: {
      created: "Created",
      accepted: "Accepted",
      preparing: "Preparing",
      assigned_runner: "Assigned Runner",
      delivering: "Delivering",
      delivered: "Delivered",
      cancelled: "Cancelled",
      pending: "Pending",
      in_progress: "In Progress",
      completed: "Completed",
      assigned: "Assigned",
      en_route: "En Route",
      approved: "Approved",
      rejected: "Rejected",
    },
  },
};
